In [2]:
import pandas as pd

In [3]:
counts = pd.read_csv("./original/GSE52778_raw_counts_GRCh38.p13_NCBI.tsv", sep="\t", index_col=0)
counts.index = counts.index.astype(str)
counts

,GSM1275862,GSM1275863,GSM1275864,GSM1275865,GSM1275866,GSM1275867,GSM1275868,GSM1275869,GSM1275870,GSM1275871,GSM1275872,GSM1275873,GSM1275874,GSM1275875,GSM1275876,GSM1275877
GeneID,,,,,,,,,,,,,,,,
100287102,6,8,8,3,5,10,11,7,6,8,4,10,2,1,2,2
653635,357,292,351,285,469,428,523,442,367,415,404,354,371,381,367,341
102466751,12,11,12,10,15,15,19,15,9,11,18,9,10,9,12,6
107985730,1,1,2,1,3,2,2,3,1,1,1,1,2,1,1,1
100302278,0,0,1,0,0,0,1,1,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4541,17596,19689,19810,24439,30975,59619,51699,33418,40220,44255,40769,31603,29123,32536,21509,30506
4556,739,860,722,981,1874,2688,2842,1745,2391,2786,2372,1668,1516,1780,1368,2023
4519,44146,48921,44199,55403,63746,137684,130735,79497,88078,98662,88642,73972,65091,84954,46869,71625
4576,79,84,83,103,174,278,249,199,176,170,143,130,113,121,104,126
4571,290,348,355,334,795,972,1059,675,991,998,1022,822,693,772,626,793

In [4]:
annot = pd.read_csv("./original/Human.GRCh38.p13.annot.tsv", sep="\t", index_col=0)
annot.index = annot.index.astype(str)
annot

/var/folders/nb/ks79gh_s30z8f_b8z00ks12w0000gn/T/ipykernel_58673/2780250041.py:1: DtypeWarning: Columns (8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  annot = pd.read_csv("./original/Human.GRCh38.p13.annot.tsv", sep="\t", index_col=0)

,Symbol,Description,Synonyms,GeneType,EnsemblGeneID,Status,ChrAcc,ChrStart,ChrStop,Orientation,Length,GOFunctionID,GOProcessID,GOComponentID,GOFunction,GOProcess,GOComponent
GeneID,,,,,,,,,,,,,,,,,
100287102,DDX11L1,DEAD/H-box helicase 11 like 1 (pseudogene),NaN,pseudo,ENSG00000290825,active,NC_000001.11,11874,14409,positive,1652,NaN,NaN,NaN,NaN,NaN,NaN
653635,WASH7P,"WASP family homolog 7, pseudogene",FAM39F|WASH5P,pseudo,NaN,active,NC_000001.11,14362,29370,negative,1769,NaN,NaN,NaN,NaN,NaN,NaN
102466751,MIR6859-1,microRNA 6859-1,hsa-mir-6859-1,ncRNA,ENSG00000278267,active,NC_000001.11,17369,17436,negative,68,NaN,NaN,NaN,NaN,NaN,NaN
107985730,MIR1302-2HG,MIR1302-2 host gene,NaN,ncRNA,NaN,active,NC_000001.11,29926,31295,positive,538,NaN,NaN,NaN,NaN,NaN,NaN
100302278,MIR1302-2,microRNA 1302-2,MIRN1302-2|hsa-mir-1302-2,ncRNA,ENSG00000284332,active,NC_000001.11,30366,30503,positive,138,NaN,GO:0035195,NaN,NaN,miRNA-mediated gene silencing,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4541,ND6,NADH dehydrogenase subunit 6,MTND6,protein-coding,NaN,active,NC_012920.1,14149,14673,negative,525,GO:0008137,GO:0006120///GO:0009060///GO:0032981///GO:0035...,GO:0005739///GO:0005743///GO:0005747,NADH dehydrogenase (ubiquinone) activity,"mitochondrial electron transport, NADH to ubiq...",mitochondrion///mitochondrial inner membrane//...
4556,TRNE,tRNA-Glu,MTTE,tRNA,NaN,active,NC_012920.1,14674,14742,negative,69,NaN,NaN,NaN,NaN,NaN,NaN
4519,CYTB,cytochrome b,MTCYB,protein-coding,NaN,active,NC_012920.1,14747,15887,positive,1141,GO:0008121///GO:0046872,GO:0006122///GO:0045333///GO:1902600,GO:0005739///GO:0005743///GO:0005750///GO:0016020,ubiquinol-cytochrome-c reductase activity///me...,"mitochondrial electron transport, ubiquinol to...",mitochondrion///mitochondrial inner membrane//...
4576,TRNT,tRNA-Thr,MTTT,tRNA,NaN,active,NC_012920.1,15888,15953,positive,66,NaN,NaN,NaN,NaN,NaN,NaN
4571,TRNP,tRNA-Pro,MTTP,tRNA,NaN,active,NC_012920.1,15956,16023,negative,68,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
count_annot = counts.merge(annot[["Symbol"]], left_index=True, right_index=True)
count_annot = count_annot.set_index("Symbol")
count_annot

,GSM1275862,GSM1275863,GSM1275864,GSM1275865,GSM1275866,GSM1275867,GSM1275868,GSM1275869,GSM1275870,GSM1275871,GSM1275872,GSM1275873,GSM1275874,GSM1275875,GSM1275876,GSM1275877
Symbol,,,,,,,,,,,,,,,,
DDX11L1,6,8,8,3,5,10,11,7,6,8,4,10,2,1,2,2
WASH7P,357,292,351,285,469,428,523,442,367,415,404,354,371,381,367,341
MIR6859-1,12,11,12,10,15,15,19,15,9,11,18,9,10,9,12,6
MIR1302-2HG,1,1,2,1,3,2,2,3,1,1,1,1,2,1,1,1
MIR1302-2,0,0,1,0,0,0,1,1,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ND6,17596,19689,19810,24439,30975,59619,51699,33418,40220,44255,40769,31603,29123,32536,21509,30506
TRNE,739,860,722,981,1874,2688,2842,1745,2391,2786,2372,1668,1516,1780,1368,2023
CYTB,44146,48921,44199,55403,63746,137684,130735,79497,88078,98662,88642,73972,65091,84954,46869,71625
TRNT,79,84,83,103,174,278,249,199,176,170,143,130,113,121,104,126
TRNP,290,348,355,334,795,972,1059,675,991,998,1022,822,693,772,626,793

In [20]:
acc_list = [ "GSM1275862", "GSM1275863", "GSM1275864", "GSM1275865", "GSM1275866", "GSM1275867", "GSM1275868", "GSM1275869", "GSM1275870", "GSM1275871", "GSM1275872", "GSM1275873", "GSM1275874", "GSM1275875", "GSM1275876", "GSM1275877"]
title_list = [
    "N61311_untreated", "N61311_Dex", "N61311_Alb", "N61311_Alb_Dex",
    "N052611_untreated", "N052611_Dex", "N052611_Alb", "N052611_Alb_Dex",
    "N080611_untreated", "N080611_Dex", "N080611_Alb", "N080611_Alb_Dex",
    "N061011_untreated", "N061011_Dex", "N061011_Alb", "N061011_Alb_Dex"
]

sample_df = pd.DataFrame(index=acc_list, data={"title": title_list})
sample_df["treatment"] = sample_df["title"].apply(lambda x: "_".join(x.split("_")[1:]))
sample_df["cell_line"] = sample_df["title"].apply(lambda x: x.split("_")[0])

sample_df = sample_df[sample_df["treatment"].isin(["untreated", "Dex"])]
sample_df = sample_df.sort_values("treatment")
sample_df

                        title  treatment cell_line
GSM1275863         N61311_Dex        Dex    N61311
GSM1275867        N052611_Dex        Dex   N052611
GSM1275871        N080611_Dex        Dex   N080611
GSM1275875        N061011_Dex        Dex   N061011
GSM1275862   N61311_untreated  untreated    N61311
GSM1275866  N052611_untreated  untreated   N052611
GSM1275870  N080611_untreated  untreated   N080611
GSM1275874  N061011_untreated  untreated   N061011

In [21]:
sample_df.reset_index(drop=True).to_csv("./csv/rnaseq_GSE52778_metadata.csv", sep=",", index=False)

In [22]:
count_annot_renamed = count_annot[sample_df.index]
count_annot_renamed = count_annot_renamed.rename(columns=sample_df["title"])
count_annot_renamed.to_csv("./csv/rnaseq_GSE52778_counts.csv", sep=",", index_label="Gene")
count_annot_renamed

,N61311_Dex,N052611_Dex,N080611_Dex,N061011_Dex,N61311_untreated,N052611_untreated,N080611_untreated,N061011_untreated
Symbol,,,,,,,,
DDX11L1,8,10,8,1,6,5,6,2
WASH7P,292,428,415,381,357,469,367,371
MIR6859-1,11,15,11,9,12,15,9,10
MIR1302-2HG,1,2,1,1,1,3,1,2
MIR1302-2,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...
ND6,19689,59619,44255,32536,17596,30975,40220,29123
TRNE,860,2688,2786,1780,739,1874,2391,1516
CYTB,48921,137684,98662,84954,44146,63746,88078,65091
TRNT,84,278,170,121,79,174,176,113
TRNP,348,972,998,772,290,795,991,693